./vialerbuild --ssl --opus --h264 --enable-ipv6 --arch=arm64,x86_64 --extra-config-site-options="PJ_IPHONE_OS_HAS_MULTITASKING_SUPPORT 1,
PJ_ACTIVESOCK_TCP_IPHONE_OS_BG 0,
PJSIP_AUTH_HEADER_CACHING 1,
PJSIP_AUTH_AUTO_SEND_NEXT 1,
PJSUA_DISABLE_AUTO_SEND_100 1"